stages:
  load_data:
    cmd: python src/load_data.py --config=config/params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - house_prices/train.csv
    outs:
    - data/raw/train.csv

  split_data:
    cmd: python src/split_data.py --config=config/params.yaml
    deps:
    - src/split_data.py
    - data/raw/train.csv
    outs:
    - data/processed/train_house_prices.csv
    - data/processed/test_house_prices.csv