stages:
  load_data:
    cmd: python src/load_data.py --config=config/params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - house_prices/train.csv
    outs:
    - data/raw/train.csv

  split_data:
    cmd: python src/split_data.py --config=config/params.yaml
    deps:
    - src/split_data.py
    - data/raw/train.csv
    outs:
    - data/processed/train_house_prices.csv
    - data/processed/test_house_prices.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=config/params.yaml
    deps:
    - data/processed/train_house_prices.csv
    - data/processed/test_house_prices.csv
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.max_depth
    - estimators.RandomForestRegressor.params.max_features
    - estimators.RandomForestRegressor.params.min_samples_split
    - estimators.RandomForestRegressor.params.n_estimators
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - models/model.joblib