base:
  project: dvc_learn
  random_state: 42
  target_col: SalePrice

data_source:
  s3_source: house_prices/train.csv

load_data:
  raw_dataset_csv: data/raw/train.csv

split_data:
  train_path: data/processed/train_house_prices.csv
  test_path: data/processed/test_house_prices.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      # max_depth: 20 
      # max_features: 0.5 
      # min_samples_split: 2 
      # n_estimators: 200
      max_depth: 25
      max_features: 0.6
      min_samples_split: 5
      n_estimators: 180


model_dir: models 

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: models/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: random forest regressor
  run_name: mlops
  registered_model_name: RandomForest
  remote_server_uri: http://0.0.0.0:1234